version: "3"
services:
  exius-system:
    restart: always
    environment: 
      VIRTUAL_HOST: subdomain.domain
      LETSENCRYPT_HOST: subdomain.domain
      LETSENCRYPT_EMAIL: example@email.com
      VIRTUAL_PORT: 3050
      ADMIN_GIT_KEY: "12345example"
      GIT_ORG: "exampleOrg"
      TEMPLATE_CREDENTIALS_NEEDED: "pull"
    build: 
      context: "./Exius"
    expose:
      - 3050
    networks:
      - service_network
    ports:
      - "3050:3050"
  nginx-proxy:
    build: "./nginx_builder"
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy
    networks:
      service_network:
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-acme:/etc/amce.sh
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-acme:/etc/amce.sh
networks:
  service_network:
volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acme: